# Generated by Django 2.2.7 on 2019-11-09 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tubook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='eventplace',
            field=models.CharField(default='', max_length=100),
        ),
    ]
