# Generated by Django 2.2.7 on 2019-11-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191110_0141'),
        ('tubook', '0002_auto_20191109_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Profile', to_field='name'),
            preserve_default=False,
        ),
    ]
