# Generated by Django 2.2.7 on 2019-11-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubook', '0004_auto_20191110_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
